/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Payload for canceling an appointment record.
 * @export
 * @interface AppointmentCancelPutPayload
 */
export interface AppointmentCancelPutPayload {
    /**
     * Sends a notification to the appointment's order's customer that the appointment was canceled.
     * @type {boolean}
     * @memberof AppointmentCancelPutPayload
     */
    notify?: boolean | null;
}

/**
 * Check if a given object implements the AppointmentCancelPutPayload interface.
 */
export function instanceOfAppointmentCancelPutPayload(value: object): value is AppointmentCancelPutPayload {
    return true;
}

export function AppointmentCancelPutPayloadFromJSON(json: any): AppointmentCancelPutPayload {
    return AppointmentCancelPutPayloadFromJSONTyped(json, false);
}

export function AppointmentCancelPutPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppointmentCancelPutPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'notify': json['notify'] == null ? undefined : json['notify'],
    };
}

export function AppointmentCancelPutPayloadToJSON(json: any): AppointmentCancelPutPayload {
    return AppointmentCancelPutPayloadToJSONTyped(json, false);
}

export function AppointmentCancelPutPayloadToJSONTyped(value?: AppointmentCancelPutPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notify': value['notify'],
    };
}

