/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Discount } from './Discount';
import {
    DiscountFromJSON,
    DiscountToJSON
} from './Discount';

/**
 * A discount amount.
 * @export
 * @interface DiscountAmount
 */
export interface DiscountAmount {
    /**
     * ID of the item. UUID Version 4.
     * @type {string}
     * @memberof DiscountAmount
     */
    id?: string;
    /**
     * 
     * @type {Discount}
     * @memberof DiscountAmount
     */
    discount?: Discount;
    /**
     * The amount of discount that was applied
     * @type {number}
     * @memberof DiscountAmount
     */
    amount?: number;
    /**
     * Representation of percent off ranging from 0 to 1
     * @type {number}
     * @memberof DiscountAmount
     */
    appliedPercentOff?: number | null;
    /**
     * Amount discounted in cents
     * @type {number}
     * @memberof DiscountAmount
     */
    appliedAmountOff?: number | null;
    /**
     * The date and time (ISO 8601 format) when the order was created.
     * @type {Date}
     * @memberof DiscountAmount
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the DiscountAmount interface.
 */
export function instanceOfDiscountAmount(value: object): value is DiscountAmount {
    return true;
}

export function DiscountAmountFromJSON(json: any): DiscountAmount {
    return DiscountAmountFromJSONTyped(json, false);
}

export function DiscountAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscountAmount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'discount': json['discount'] == null ? undefined : DiscountFromJSON(json['discount']),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'appliedPercentOff': json['applied_percent_off'] == null ? undefined : json['applied_percent_off'],
        'appliedAmountOff': json['applied_amount_off'] == null ? undefined : json['applied_amount_off'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function DiscountAmountToJSON(json: any): DiscountAmount {
    return DiscountAmountToJSONTyped(json, false);
}

export function DiscountAmountToJSONTyped(value?: DiscountAmount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'discount': DiscountToJSON(value['discount']),
        'amount': value['amount'],
        'applied_percent_off': value['appliedPercentOff'],
        'applied_amount_off': value['appliedAmountOff'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
    };
}

