/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A discountable maps a coupon to a product or fee the coupon should exclusively apply to. 
 * @export
 * @interface Discountable
 */
export interface Discountable {
    /**
     * String representing the object’s type. Objects of the same type share the same schema.
     * @type {string}
     * @memberof Discountable
     */
    object?: string;
    /**
     * ID of the discountable. UUID Version 4.
     * @type {string}
     * @memberof Discountable
     */
    id: string;
    /**
     * A resource representing a Fee or a Product.
     * @type {object}
     * @memberof Discountable
     */
    discountable?: object;
}

/**
 * Check if a given object implements the Discountable interface.
 */
export function instanceOfDiscountable(value: object): value is Discountable {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DiscountableFromJSON(json: any): Discountable {
    return DiscountableFromJSONTyped(json, false);
}

export function DiscountableFromJSONTyped(json: any, ignoreDiscriminator: boolean): Discountable {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'] == null ? undefined : json['object'],
        'id': json['id'],
        'discountable': json['discountable'] == null ? undefined : json['discountable'],
    };
}

export function DiscountableToJSON(json: any): Discountable {
    return DiscountableToJSONTyped(json, false);
}

export function DiscountableToJSONTyped(value?: Discountable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'id': value['id'],
        'discountable': value['discountable'],
    };
}

