/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListingMarketingContent } from './ListingMarketingContent';
import {
    ListingMarketingContentFromJSON,
    ListingMarketingContentToJSON
} from './ListingMarketingContent';

/**
 * A listing's marketing content.
 * @export
 * @interface ListingMarketingContentResource
 */
export interface ListingMarketingContentResource {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof ListingMarketingContentResource
     */
    status: string;
    /**
     * 
     * @type {ListingMarketingContent}
     * @memberof ListingMarketingContentResource
     */
    data?: ListingMarketingContent;
}

/**
 * Check if a given object implements the ListingMarketingContentResource interface.
 */
export function instanceOfListingMarketingContentResource(value: object): value is ListingMarketingContentResource {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ListingMarketingContentResourceFromJSON(json: any): ListingMarketingContentResource {
    return ListingMarketingContentResourceFromJSONTyped(json, false);
}

export function ListingMarketingContentResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingMarketingContentResource {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : ListingMarketingContentFromJSON(json['data']),
    };
}

export function ListingMarketingContentResourceToJSON(json: any): ListingMarketingContentResource {
    return ListingMarketingContentResourceToJSONTyped(json, false);
}

export function ListingMarketingContentResourceToJSONTyped(value?: ListingMarketingContentResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': ListingMarketingContentToJSON(value['data']),
    };
}

