/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A client, or device, type.
 * @export
 * @interface LoginViaTokenPostPayload
 */
export interface LoginViaTokenPostPayload {
    /**
     * The type of client.
     * @type {string}
     * @memberof LoginViaTokenPostPayload
     */
    client: LoginViaTokenPostPayloadClientEnum;
}


/**
 * @export
 */
export const LoginViaTokenPostPayloadClientEnum = {
    Ios: 'IOS',
    Android: 'ANDROID',
    Phpunit: 'PHPUNIT'
} as const;
export type LoginViaTokenPostPayloadClientEnum = typeof LoginViaTokenPostPayloadClientEnum[keyof typeof LoginViaTokenPostPayloadClientEnum];


/**
 * Check if a given object implements the LoginViaTokenPostPayload interface.
 */
export function instanceOfLoginViaTokenPostPayload(value: object): value is LoginViaTokenPostPayload {
    if (!('client' in value) || value['client'] === undefined) return false;
    return true;
}

export function LoginViaTokenPostPayloadFromJSON(json: any): LoginViaTokenPostPayload {
    return LoginViaTokenPostPayloadFromJSONTyped(json, false);
}

export function LoginViaTokenPostPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginViaTokenPostPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'client': json['client'],
    };
}

export function LoginViaTokenPostPayloadToJSON(json: any): LoginViaTokenPostPayload {
    return LoginViaTokenPostPayloadToJSONTyped(json, false);
}

export function LoginViaTokenPostPayloadToJSONTyped(value?: LoginViaTokenPostPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client': value['client'],
    };
}

