/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Payload for publishing a marketing material record.
 * @export
 * @interface MarketingMaterialPublishPayload
 */
export interface MarketingMaterialPublishPayload {
    /**
     * String representation of a polotno JSON object.
     * @type {string}
     * @memberof MarketingMaterialPublishPayload
     */
    polotnoJson?: string | null;
}

/**
 * Check if a given object implements the MarketingMaterialPublishPayload interface.
 */
export function instanceOfMarketingMaterialPublishPayload(value: object): value is MarketingMaterialPublishPayload {
    return true;
}

export function MarketingMaterialPublishPayloadFromJSON(json: any): MarketingMaterialPublishPayload {
    return MarketingMaterialPublishPayloadFromJSONTyped(json, false);
}

export function MarketingMaterialPublishPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketingMaterialPublishPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'polotnoJson': json['polotno_json'] == null ? undefined : json['polotno_json'],
    };
}

export function MarketingMaterialPublishPayloadToJSON(json: any): MarketingMaterialPublishPayload {
    return MarketingMaterialPublishPayloadToJSONTyped(json, false);
}

export function MarketingMaterialPublishPayloadToJSONTyped(value?: MarketingMaterialPublishPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'polotno_json': value['polotnoJson'],
    };
}

