/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PolotnoJson } from './PolotnoJson';
import {
    PolotnoJsonFromJSON,
    PolotnoJsonToJSON
} from './PolotnoJson';

/**
 * A marketing material record.
 * @export
 * @interface MarketingMaterial
 */
export interface MarketingMaterial {
    /**
     * The ID of the marketing material. UUID Version 4.
     * @type {string}
     * @memberof MarketingMaterial
     */
    id?: string | null;
    /**
     * The name of the marketing material.
     * @type {string}
     * @memberof MarketingMaterial
     */
    name?: string | null;
    /**
     * A URL for a thumbnail-sized preview of the marketing material.
     * @type {string}
     * @memberof MarketingMaterial
     */
    thumbnailUrl?: string;
    /**
     * The date and time (ISO 8601 format) when the marketing material record was last published.
     * @type {Date}
     * @memberof MarketingMaterial
     */
    publishedAt?: Date | null;
    /**
     * 
     * @type {PolotnoJson}
     * @memberof MarketingMaterial
     */
    polotnoJson?: PolotnoJson;
    /**
     * The ID of the listing the marketing material belongs to. UUID Version 4.
     * @type {string}
     * @memberof MarketingMaterial
     */
    listingDownloadHash?: string | null;
    /**
     * Timestamp of when the polotno_json field was last updated.
     * @type {number}
     * @memberof MarketingMaterial
     */
    jsonUpdatedAt?: number | null;
}

/**
 * Check if a given object implements the MarketingMaterial interface.
 */
export function instanceOfMarketingMaterial(value: object): value is MarketingMaterial {
    return true;
}

export function MarketingMaterialFromJSON(json: any): MarketingMaterial {
    return MarketingMaterialFromJSONTyped(json, false);
}

export function MarketingMaterialFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketingMaterial {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'thumbnailUrl': json['thumbnail_url'] == null ? undefined : json['thumbnail_url'],
        'publishedAt': json['published_at'] == null ? undefined : (new Date(json['published_at'])),
        'polotnoJson': json['polotno_json'] == null ? undefined : PolotnoJsonFromJSON(json['polotno_json']),
        'listingDownloadHash': json['listing_download_hash'] == null ? undefined : json['listing_download_hash'],
        'jsonUpdatedAt': json['json_updated_at'] == null ? undefined : json['json_updated_at'],
    };
}

export function MarketingMaterialToJSON(json: any): MarketingMaterial {
    return MarketingMaterialToJSONTyped(json, false);
}

export function MarketingMaterialToJSONTyped(value?: MarketingMaterial | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'thumbnail_url': value['thumbnailUrl'],
        'published_at': value['publishedAt'] == null ? undefined : ((value['publishedAt'] as any).toISOString()),
        'polotno_json': PolotnoJsonToJSON(value['polotnoJson']),
        'listing_download_hash': value['listingDownloadHash'],
        'json_updated_at': value['jsonUpdatedAt'],
    };
}

