/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A defined page size for marketing material.
 * @export
 * @interface MarketingMaterialPageSize
 */
export interface MarketingMaterialPageSize {
    /**
     * ID of the page size. UUID Version 4.
     * @type {string}
     * @memberof MarketingMaterialPageSize
     */
    id: string;
    /**
     * Width in pixels.
     * @type {number}
     * @memberof MarketingMaterialPageSize
     */
    width: number;
    /**
     * Height in pixels.
     * @type {number}
     * @memberof MarketingMaterialPageSize
     */
    height: number;
    /**
     * Name of the page size.
     * @type {string}
     * @memberof MarketingMaterialPageSize
     */
    name: string;
}

/**
 * Check if a given object implements the MarketingMaterialPageSize interface.
 */
export function instanceOfMarketingMaterialPageSize(value: object): value is MarketingMaterialPageSize {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('height' in value) || value['height'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MarketingMaterialPageSizeFromJSON(json: any): MarketingMaterialPageSize {
    return MarketingMaterialPageSizeFromJSONTyped(json, false);
}

export function MarketingMaterialPageSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketingMaterialPageSize {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'width': json['width'],
        'height': json['height'],
        'name': json['name'],
    };
}

export function MarketingMaterialPageSizeToJSON(json: any): MarketingMaterialPageSize {
    return MarketingMaterialPageSizeToJSONTyped(json, false);
}

export function MarketingMaterialPageSizeToJSONTyped(value?: MarketingMaterialPageSize | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'width': value['width'],
        'height': value['height'],
        'name': value['name'],
    };
}

