/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MarketingMaterial } from './MarketingMaterial';
import {
    MarketingMaterialFromJSON,
    MarketingMaterialToJSON
} from './MarketingMaterial';

/**
 * Marketing material.
 * @export
 * @interface MarketingMaterialResource
 */
export interface MarketingMaterialResource {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof MarketingMaterialResource
     */
    status: string;
    /**
     * 
     * @type {MarketingMaterial}
     * @memberof MarketingMaterialResource
     */
    data?: MarketingMaterial;
}

/**
 * Check if a given object implements the MarketingMaterialResource interface.
 */
export function instanceOfMarketingMaterialResource(value: object): value is MarketingMaterialResource {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function MarketingMaterialResourceFromJSON(json: any): MarketingMaterialResource {
    return MarketingMaterialResourceFromJSONTyped(json, false);
}

export function MarketingMaterialResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketingMaterialResource {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : MarketingMaterialFromJSON(json['data']),
    };
}

export function MarketingMaterialResourceToJSON(json: any): MarketingMaterialResource {
    return MarketingMaterialResourceToJSONTyped(json, false);
}

export function MarketingMaterialResourceToJSONTyped(value?: MarketingMaterialResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': MarketingMaterialToJSON(value['data']),
    };
}

