/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A request to change the currently authenticated user's password.
 * @export
 * @interface MePasswordPutPayload
 */
export interface MePasswordPutPayload {
    /**
     * A user's current password.
     * @type {string}
     * @memberof MePasswordPutPayload
     */
    currentPassword: string;
    /**
     * A new password.
     * @type {string}
     * @memberof MePasswordPutPayload
     */
    newPassword: string;
    /**
     * A copy of the new password for confirmation purposes.
     * @type {string}
     * @memberof MePasswordPutPayload
     */
    newPasswordConfirmation: string;
}

/**
 * Check if a given object implements the MePasswordPutPayload interface.
 */
export function instanceOfMePasswordPutPayload(value: object): value is MePasswordPutPayload {
    if (!('currentPassword' in value) || value['currentPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('newPasswordConfirmation' in value) || value['newPasswordConfirmation'] === undefined) return false;
    return true;
}

export function MePasswordPutPayloadFromJSON(json: any): MePasswordPutPayload {
    return MePasswordPutPayloadFromJSONTyped(json, false);
}

export function MePasswordPutPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MePasswordPutPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['current_password'],
        'newPassword': json['new_password'],
        'newPasswordConfirmation': json['new_password_confirmation'],
    };
}

export function MePasswordPutPayloadToJSON(json: any): MePasswordPutPayload {
    return MePasswordPutPayloadToJSONTyped(json, false);
}

export function MePasswordPutPayloadToJSONTyped(value?: MePasswordPutPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_password': value['currentPassword'],
        'new_password': value['newPassword'],
        'new_password_confirmation': value['newPasswordConfirmation'],
    };
}

