/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NotificationPreferences } from './NotificationPreferences';
import {
    NotificationPreferencesFromJSON,
    NotificationPreferencesToJSON
} from './NotificationPreferences';

/**
 * A collection of notification preferences.
 * @export
 * @interface NotificationPreferencesCollection
 */
export interface NotificationPreferencesCollection {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof NotificationPreferencesCollection
     */
    status: string;
    /**
     * A collection of objects.
     * @type {Array<NotificationPreferences>}
     * @memberof NotificationPreferencesCollection
     */
    data?: Array<NotificationPreferences> | null;
}

/**
 * Check if a given object implements the NotificationPreferencesCollection interface.
 */
export function instanceOfNotificationPreferencesCollection(value: object): value is NotificationPreferencesCollection {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function NotificationPreferencesCollectionFromJSON(json: any): NotificationPreferencesCollection {
    return NotificationPreferencesCollectionFromJSONTyped(json, false);
}

export function NotificationPreferencesCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationPreferencesCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(NotificationPreferencesFromJSON)),
    };
}

export function NotificationPreferencesCollectionToJSON(json: any): NotificationPreferencesCollection {
    return NotificationPreferencesCollectionToJSONTyped(json, false);
}

export function NotificationPreferencesCollectionToJSONTyped(value?: NotificationPreferencesCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(NotificationPreferencesToJSON)),
    };
}

