/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderToJSON
} from './Order';
import type { PaginationLinks } from './PaginationLinks';
import {
    PaginationLinksFromJSON,
    PaginationLinksToJSON
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaToJSON
} from './PaginationMeta';

/**
 * A collection of orders.
 * @export
 * @interface OrderCollection
 */
export interface OrderCollection {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof OrderCollection
     */
    status: string;
    /**
     * A collection of objects.
     * @type {Array<Order>}
     * @memberof OrderCollection
     */
    data?: Array<Order> | null;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof OrderCollection
     */
    meta?: PaginationMeta;
    /**
     * 
     * @type {PaginationLinks}
     * @memberof OrderCollection
     */
    links?: PaginationLinks;
}

/**
 * Check if a given object implements the OrderCollection interface.
 */
export function instanceOfOrderCollection(value: object): value is OrderCollection {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OrderCollectionFromJSON(json: any): OrderCollection {
    return OrderCollectionFromJSONTyped(json, false);
}

export function OrderCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(OrderFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
        'links': json['links'] == null ? undefined : PaginationLinksFromJSON(json['links']),
    };
}

export function OrderCollectionToJSON(json: any): OrderCollection {
    return OrderCollectionToJSONTyped(json, false);
}

export function OrderCollectionToJSONTyped(value?: OrderCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(OrderToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
        'links': PaginationLinksToJSON(value['links']),
    };
}

