/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OrderFormSessionPostPayloadAddressData } from './OrderFormSessionPostPayloadAddressData';
import {
    OrderFormSessionPostPayloadAddressDataFromJSON,
    OrderFormSessionPostPayloadAddressDataToJSON
} from './OrderFormSessionPostPayloadAddressData';
import type { OrderFormSessionPostPayloadCustomerData } from './OrderFormSessionPostPayloadCustomerData';
import {
    OrderFormSessionPostPayloadCustomerDataFromJSON,
    OrderFormSessionPostPayloadCustomerDataToJSON
} from './OrderFormSessionPostPayloadCustomerData';
import type { OrderFormSessionPostPayloadStepVisibility } from './OrderFormSessionPostPayloadStepVisibility';
import {
    OrderFormSessionPostPayloadStepVisibilityFromJSON,
    OrderFormSessionPostPayloadStepVisibilityToJSON
} from './OrderFormSessionPostPayloadStepVisibility';

/**
 * Payload for creating an OrderFormSession to be used for an order form.
 * @export
 * @interface OrderFormSessionPostPayload
 */
export interface OrderFormSessionPostPayload {
    /**
     * ID of an order form to associate with the order form session. UUID Version 4.
     * @type {string}
     * @memberof OrderFormSessionPostPayload
     */
    orderFormId: string;
    /**
     * ID of an address to associate with the order form session. UUID Version 4.
     * @type {string}
     * @memberof OrderFormSessionPostPayload
     */
    addressId?: string;
    /**
     * 
     * @type {OrderFormSessionPostPayloadAddressData}
     * @memberof OrderFormSessionPostPayload
     */
    addressData?: OrderFormSessionPostPayloadAddressData;
    /**
     * ID of the customer to associate with the order form session. UUID Version 4.
     * @type {string}
     * @memberof OrderFormSessionPostPayload
     */
    customerId?: string;
    /**
     * ID of the customer group to associate with the order form session. UUID Version 4.
     * @type {string}
     * @memberof OrderFormSessionPostPayload
     */
    customerGroupId?: string;
    /**
     * 
     * @type {OrderFormSessionPostPayloadCustomerData}
     * @memberof OrderFormSessionPostPayload
     */
    customerData?: OrderFormSessionPostPayloadCustomerData;
    /**
     * IDs of the coupons to associate with this order. 
     * @type {Array<string>}
     * @memberof OrderFormSessionPostPayload
     */
    couponIds?: Array<string>;
    /**
     * 
     * @type {OrderFormSessionPostPayloadStepVisibility}
     * @memberof OrderFormSessionPostPayload
     */
    stepVisibility?: OrderFormSessionPostPayloadStepVisibility;
    /**
     * The URL the customer will be directed to after the payment or order placement is successful. By default, customers are directed to the Aryeo order confirmation page.
     * @type {string}
     * @memberof OrderFormSessionPostPayload
     */
    successUrl?: string;
}

/**
 * Check if a given object implements the OrderFormSessionPostPayload interface.
 */
export function instanceOfOrderFormSessionPostPayload(value: object): value is OrderFormSessionPostPayload {
    if (!('orderFormId' in value) || value['orderFormId'] === undefined) return false;
    return true;
}

export function OrderFormSessionPostPayloadFromJSON(json: any): OrderFormSessionPostPayload {
    return OrderFormSessionPostPayloadFromJSONTyped(json, false);
}

export function OrderFormSessionPostPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderFormSessionPostPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'orderFormId': json['order_form_id'],
        'addressId': json['address_id'] == null ? undefined : json['address_id'],
        'addressData': json['address_data'] == null ? undefined : OrderFormSessionPostPayloadAddressDataFromJSON(json['address_data']),
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'customerGroupId': json['customer_group_id'] == null ? undefined : json['customer_group_id'],
        'customerData': json['customer_data'] == null ? undefined : OrderFormSessionPostPayloadCustomerDataFromJSON(json['customer_data']),
        'couponIds': json['coupon_ids'] == null ? undefined : json['coupon_ids'],
        'stepVisibility': json['step_visibility'] == null ? undefined : OrderFormSessionPostPayloadStepVisibilityFromJSON(json['step_visibility']),
        'successUrl': json['success_url'] == null ? undefined : json['success_url'],
    };
}

export function OrderFormSessionPostPayloadToJSON(json: any): OrderFormSessionPostPayload {
    return OrderFormSessionPostPayloadToJSONTyped(json, false);
}

export function OrderFormSessionPostPayloadToJSONTyped(value?: OrderFormSessionPostPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_form_id': value['orderFormId'],
        'address_id': value['addressId'],
        'address_data': OrderFormSessionPostPayloadAddressDataToJSON(value['addressData']),
        'customer_id': value['customerId'],
        'customer_group_id': value['customerGroupId'],
        'customer_data': OrderFormSessionPostPayloadCustomerDataToJSON(value['customerData']),
        'coupon_ids': value['couponIds'],
        'step_visibility': OrderFormSessionPostPayloadStepVisibilityToJSON(value['stepVisibility']),
        'success_url': value['successUrl'],
    };
}

