/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Payload for creating an order item.
 * @export
 * @interface OrderItemPostPayload
 */
export interface OrderItemPostPayload {
    /**
     * ID of the order to associate this order item to. UUID Version 4.
     * @type {string}
     * @memberof OrderItemPostPayload
     */
    orderId: string;
    /**
     * ID of the product variant to create this order item from. UUID Version 4.
     * @type {string}
     * @memberof OrderItemPostPayload
     */
    productVariantId?: string;
    /**
     * A positive integer representing the number of instances of this item that was or will be serviced.
     * @type {number}
     * @memberof OrderItemPostPayload
     */
    quantity?: number;
    /**
     * A positive integer in the smallest currency unit (that is, 100 cents for $1.00) representing the cost of a single instance of this item. This is multiplied by the quantity to calculate what was or will be charged. Required when a product variant ID is not specified.
     * @type {number}
     * @memberof OrderItemPostPayload
     */
    unitPriceAmount?: number;
    /**
     * The title of the item. Required when a product variant ID is not specified.
     * @type {string}
     * @memberof OrderItemPostPayload
     */
    title?: string;
    /**
     * The subtitle of the item. Required when a product variant ID is not specified.
     * @type {string}
     * @memberof OrderItemPostPayload
     */
    subtitle?: string;
    /**
     * The description of the item. Required when a product variant ID is not specified.
     * @type {string}
     * @memberof OrderItemPostPayload
     */
    description?: string;
    /**
     * ID of the appointment that is scheduled to service this order item. UUID Version 4.
     * @type {string}
     * @memberof OrderItemPostPayload
     */
    appointmentId?: string;
    /**
     * ID of the company team member assigned to this order item. UUID Version 4.
     * @type {string}
     * @memberof OrderItemPostPayload
     */
    assignedCompanyTeamMemberId?: string;
}

/**
 * Check if a given object implements the OrderItemPostPayload interface.
 */
export function instanceOfOrderItemPostPayload(value: object): value is OrderItemPostPayload {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    return true;
}

export function OrderItemPostPayloadFromJSON(json: any): OrderItemPostPayload {
    return OrderItemPostPayloadFromJSONTyped(json, false);
}

export function OrderItemPostPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItemPostPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['order_id'],
        'productVariantId': json['product_variant_id'] == null ? undefined : json['product_variant_id'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'unitPriceAmount': json['unit_price_amount'] == null ? undefined : json['unit_price_amount'],
        'title': json['title'] == null ? undefined : json['title'],
        'subtitle': json['subtitle'] == null ? undefined : json['subtitle'],
        'description': json['description'] == null ? undefined : json['description'],
        'appointmentId': json['appointment_id'] == null ? undefined : json['appointment_id'],
        'assignedCompanyTeamMemberId': json['assigned_company_team_member_id'] == null ? undefined : json['assigned_company_team_member_id'],
    };
}

export function OrderItemPostPayloadToJSON(json: any): OrderItemPostPayload {
    return OrderItemPostPayloadToJSONTyped(json, false);
}

export function OrderItemPostPayloadToJSONTyped(value?: OrderItemPostPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_id': value['orderId'],
        'product_variant_id': value['productVariantId'],
        'quantity': value['quantity'],
        'unit_price_amount': value['unitPriceAmount'],
        'title': value['title'],
        'subtitle': value['subtitle'],
        'description': value['description'],
        'appointment_id': value['appointmentId'],
        'assigned_company_team_member_id': value['assignedCompanyTeamMemberId'],
    };
}

