/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Variants of this products.
 * @export
 * @interface OrderPostPayloadProductItemsInner
 */
export interface OrderPostPayloadProductItemsInner {
    /**
     * ID of the product variant to associate with the order item. UUID Version 4.
     * @type {string}
     * @memberof OrderPostPayloadProductItemsInner
     */
    variantId?: string;
    /**
     * A positive integer representing the number of instances of this item that was or will be serviced.
     * @type {number}
     * @memberof OrderPostPayloadProductItemsInner
     */
    quantity?: number;
}

/**
 * Check if a given object implements the OrderPostPayloadProductItemsInner interface.
 */
export function instanceOfOrderPostPayloadProductItemsInner(value: object): value is OrderPostPayloadProductItemsInner {
    return true;
}

export function OrderPostPayloadProductItemsInnerFromJSON(json: any): OrderPostPayloadProductItemsInner {
    return OrderPostPayloadProductItemsInnerFromJSONTyped(json, false);
}

export function OrderPostPayloadProductItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderPostPayloadProductItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'variantId': json['variant_id'] == null ? undefined : json['variant_id'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function OrderPostPayloadProductItemsInnerToJSON(json: any): OrderPostPayloadProductItemsInner {
    return OrderPostPayloadProductItemsInnerToJSONTyped(json, false);
}

export function OrderPostPayloadProductItemsInnerToJSONTyped(value?: OrderPostPayloadProductItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'variant_id': value['variantId'],
        'quantity': value['quantity'],
    };
}

