/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An order form is a form that is used to submit an order.
 * @export
 * @interface OrderForm
 */
export interface OrderForm {
    /**
     * ID of the order form. UUID Version 4.
     * @type {string}
     * @memberof OrderForm
     */
    id: string;
    /**
     * The title or name of the order form.
     * @type {string}
     * @memberof OrderForm
     */
    title: string;
    /**
     * The type of the order form, indicating whether the order form is an Aryeo order form or that of another scheduling service provider.
     * @type {string}
     * @memberof OrderForm
     */
    type: OrderFormTypeEnum;
    /**
     * A URL of a publicly-accessible webpage for this order form.
     * @type {string}
     * @memberof OrderForm
     */
    url: string;
    /**
     * Indicates if the order form is uses territories to filter available users and products.
     * @type {boolean}
     * @memberof OrderForm
     */
    useTerritoryAwareness?: boolean;
    /**
     * The scheduling style the order form should use to for timeslot selection.
     * @type {string}
     * @memberof OrderForm
     */
    availabilityStyle?: OrderFormAvailabilityStyleEnum;
    /**
     * How frequently slotted available times are on the order form.
     * @type {number}
     * @memberof OrderForm
     */
    slotIntervalMinutes?: number;
    /**
     * Indicates if the order form users auto-assignment of users to appointments.
     * @type {boolean}
     * @memberof OrderForm
     */
    useAutomatedUserAssignment?: boolean;
    /**
     * The assignment strategy the order form should use to assign users to appointments, if applicable.
     * @type {string}
     * @memberof OrderForm
     */
    automatedUserAssignmentStrategy?: OrderFormAutomatedUserAssignmentStrategyEnum;
    /**
     * Indicates if the order form should display user's names after they have been assigned to an appointment.
     * @type {boolean}
     * @memberof OrderForm
     */
    showUserNames?: boolean;
    /**
     * Indicates if the order form requires an upfront payment to place the order. 
     * @type {boolean}
     * @memberof OrderForm
     */
    requireUpfrontPayment?: boolean;
    /**
     * The percentage of the order form's total price that should be paid upfront.
     * @type {number}
     * @memberof OrderForm
     */
    upfrontPaymentPercentage?: number | null;
    /**
     * Indicates if the order form instantly schedules appointments as soon as the order is placed.
     * @type {boolean}
     * @memberof OrderForm
     */
    useInstantAppointmentScheduling?: boolean;
}


/**
 * @export
 */
export const OrderFormTypeEnum = {
    Aryeo: 'ARYEO',
    External: 'EXTERNAL'
} as const;
export type OrderFormTypeEnum = typeof OrderFormTypeEnum[keyof typeof OrderFormTypeEnum];

/**
 * @export
 */
export const OrderFormAvailabilityStyleEnum = {
    Time: 'TIME',
    TimeOfDay: 'TIME_OF_DAY',
    Legacy: 'LEGACY'
} as const;
export type OrderFormAvailabilityStyleEnum = typeof OrderFormAvailabilityStyleEnum[keyof typeof OrderFormAvailabilityStyleEnum];

/**
 * @export
 */
export const OrderFormAutomatedUserAssignmentStrategyEnum = {
    Recommended: 'RECOMMENDED',
    HoursPriority: 'HOURS_PRIORITY',
    Distance: 'DISTANCE',
    RoundRobin: 'ROUND_ROBIN',
    PriorityList: 'PRIORITY_LIST'
} as const;
export type OrderFormAutomatedUserAssignmentStrategyEnum = typeof OrderFormAutomatedUserAssignmentStrategyEnum[keyof typeof OrderFormAutomatedUserAssignmentStrategyEnum];


/**
 * Check if a given object implements the OrderForm interface.
 */
export function instanceOfOrderForm(value: object): value is OrderForm {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function OrderFormFromJSON(json: any): OrderForm {
    return OrderFormFromJSONTyped(json, false);
}

export function OrderFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderForm {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'type': json['type'],
        'url': json['url'],
        'useTerritoryAwareness': json['use_territory_awareness'] == null ? undefined : json['use_territory_awareness'],
        'availabilityStyle': json['availability_style'] == null ? undefined : json['availability_style'],
        'slotIntervalMinutes': json['slot_interval_minutes'] == null ? undefined : json['slot_interval_minutes'],
        'useAutomatedUserAssignment': json['use_automated_user_assignment'] == null ? undefined : json['use_automated_user_assignment'],
        'automatedUserAssignmentStrategy': json['automated_user_assignment_strategy'] == null ? undefined : json['automated_user_assignment_strategy'],
        'showUserNames': json['show_user_names'] == null ? undefined : json['show_user_names'],
        'requireUpfrontPayment': json['require_upfront_payment'] == null ? undefined : json['require_upfront_payment'],
        'upfrontPaymentPercentage': json['upfront_payment_percentage'] == null ? undefined : json['upfront_payment_percentage'],
        'useInstantAppointmentScheduling': json['use_instant_appointment_scheduling'] == null ? undefined : json['use_instant_appointment_scheduling'],
    };
}

export function OrderFormToJSON(json: any): OrderForm {
    return OrderFormToJSONTyped(json, false);
}

export function OrderFormToJSONTyped(value?: OrderForm | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'type': value['type'],
        'url': value['url'],
        'use_territory_awareness': value['useTerritoryAwareness'],
        'availability_style': value['availabilityStyle'],
        'slot_interval_minutes': value['slotIntervalMinutes'],
        'use_automated_user_assignment': value['useAutomatedUserAssignment'],
        'automated_user_assignment_strategy': value['automatedUserAssignmentStrategy'],
        'show_user_names': value['showUserNames'],
        'require_upfront_payment': value['requireUpfrontPayment'],
        'upfront_payment_percentage': value['upfrontPaymentPercentage'],
        'use_instant_appointment_scheduling': value['useInstantAppointmentScheduling'],
    };
}

