/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GroupCustomer } from './GroupCustomer';
import {
    GroupCustomerFromJSON,
    GroupCustomerToJSON
} from './GroupCustomer';
import type { User } from './User';
import {
    UserFromJSON,
    UserToJSON
} from './User';

/**
 * A personal access token, its user, and the it's users group (if applicable).
 * @export
 * @interface PersonalAccessTokenCustomer
 */
export interface PersonalAccessTokenCustomer {
    /**
     * Authorization token for a user.
     * @type {string}
     * @memberof PersonalAccessTokenCustomer
     */
    token: string;
    /**
     * 
     * @type {User}
     * @memberof PersonalAccessTokenCustomer
     */
    user: User;
    /**
     * 
     * @type {GroupCustomer}
     * @memberof PersonalAccessTokenCustomer
     */
    group?: GroupCustomer;
}

/**
 * Check if a given object implements the PersonalAccessTokenCustomer interface.
 */
export function instanceOfPersonalAccessTokenCustomer(value: object): value is PersonalAccessTokenCustomer {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function PersonalAccessTokenCustomerFromJSON(json: any): PersonalAccessTokenCustomer {
    return PersonalAccessTokenCustomerFromJSONTyped(json, false);
}

export function PersonalAccessTokenCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalAccessTokenCustomer {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'user': UserFromJSON(json['user']),
        'group': json['group'] == null ? undefined : GroupCustomerFromJSON(json['group']),
    };
}

export function PersonalAccessTokenCustomerToJSON(json: any): PersonalAccessTokenCustomer {
    return PersonalAccessTokenCustomerToJSONTyped(json, false);
}

export function PersonalAccessTokenCustomerToJSONTyped(value?: PersonalAccessTokenCustomer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'user': UserToJSON(value['user']),
        'group': GroupCustomerToJSON(value['group']),
    };
}

