/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PaginationLinks } from './PaginationLinks';
import {
    PaginationLinksFromJSON,
    PaginationLinksToJSON
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaToJSON
} from './PaginationMeta';
import type { ProductCategory } from './ProductCategory';
import {
    ProductCategoryFromJSON,
    ProductCategoryToJSON
} from './ProductCategory';

/**
 * A collection of product categories.
 * @export
 * @interface ProductCategoryCollection
 */
export interface ProductCategoryCollection {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof ProductCategoryCollection
     */
    status: string;
    /**
     * 
     * @type {Array<ProductCategory>}
     * @memberof ProductCategoryCollection
     */
    data?: Array<ProductCategory> | null;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ProductCategoryCollection
     */
    meta?: PaginationMeta;
    /**
     * 
     * @type {PaginationLinks}
     * @memberof ProductCategoryCollection
     */
    links?: PaginationLinks;
}

/**
 * Check if a given object implements the ProductCategoryCollection interface.
 */
export function instanceOfProductCategoryCollection(value: object): value is ProductCategoryCollection {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ProductCategoryCollectionFromJSON(json: any): ProductCategoryCollection {
    return ProductCategoryCollectionFromJSONTyped(json, false);
}

export function ProductCategoryCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCategoryCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ProductCategoryFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
        'links': json['links'] == null ? undefined : PaginationLinksFromJSON(json['links']),
    };
}

export function ProductCategoryCollectionToJSON(json: any): ProductCategoryCollection {
    return ProductCategoryCollectionToJSONTyped(json, false);
}

export function ProductCategoryCollectionToJSONTyped(value?: ProductCategoryCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ProductCategoryToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
        'links': PaginationLinksToJSON(value['links']),
    };
}

