/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A variant of a product.
 * @export
 * @interface ProductVariant
 */
export interface ProductVariant {
    /**
     * ID of the product variant. UUID Version 4.
     * @type {string}
     * @memberof ProductVariant
     */
    id: string;
    /**
     * The title of the product variant.
     * @type {string}
     * @memberof ProductVariant
     */
    title: string;
    /**
     * A positive integer in the smallest currency unit (that is, 100 cents for $1.00) representing the price of the product variant.
     * @type {number}
     * @memberof ProductVariant
     */
    priceAmount?: number;
    /**
     * The duration of the product item, in minutes.
     * @type {number}
     * @memberof ProductVariant
     */
    duration?: number;
}

/**
 * Check if a given object implements the ProductVariant interface.
 */
export function instanceOfProductVariant(value: object): value is ProductVariant {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ProductVariantFromJSON(json: any): ProductVariant {
    return ProductVariantFromJSONTyped(json, false);
}

export function ProductVariantFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductVariant {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'priceAmount': json['price_amount'] == null ? undefined : json['price_amount'],
        'duration': json['duration'] == null ? undefined : json['duration'],
    };
}

export function ProductVariantToJSON(json: any): ProductVariant {
    return ProductVariantToJSONTyped(json, false);
}

export function ProductVariantToJSONTyped(value?: ProductVariant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'price_amount': value['priceAmount'],
        'duration': value['duration'],
    };
}

