/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A Promotion Code represents a customer-redeemable code for a coupon.
 * @export
 * @interface PromotionCode
 */
export interface PromotionCode {
    /**
     * ID of the coupon. UUID Version 4.
     * @type {string}
     * @memberof PromotionCode
     */
    id: string;
    /**
     * The customer-facing code. This code must be unique across all active promotion codes.
     * @type {string}
     * @memberof PromotionCode
     */
    code: string;
}

/**
 * Check if a given object implements the PromotionCode interface.
 */
export function instanceOfPromotionCode(value: object): value is PromotionCode {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function PromotionCodeFromJSON(json: any): PromotionCode {
    return PromotionCodeFromJSONTyped(json, false);
}

export function PromotionCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PromotionCode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'code': json['code'],
    };
}

export function PromotionCodeToJSON(json: any): PromotionCode {
    return PromotionCodeToJSONTyped(json, false);
}

export function PromotionCodeToJSONTyped(value?: PromotionCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
    };
}

