/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A SSO Provider contains the information pertaining to the SSO connection.
 * @export
 * @interface SsoProvider
 */
export interface SsoProvider {
    /**
     * Name of the provider
     * @type {string}
     * @memberof SsoProvider
     */
    name: string;
    /**
     * Technology of the provider
     * @type {string}
     * @memberof SsoProvider
     */
    provider: string;
}

/**
 * Check if a given object implements the SsoProvider interface.
 */
export function instanceOfSsoProvider(value: object): value is SsoProvider {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function SsoProviderFromJSON(json: any): SsoProvider {
    return SsoProviderFromJSONTyped(json, false);
}

export function SsoProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): SsoProvider {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'provider': json['provider'],
    };
}

export function SsoProviderToJSON(json: any): SsoProvider {
    return SsoProviderToJSONTyped(json, false);
}

export function SsoProviderToJSONTyped(value?: SsoProvider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'provider': value['provider'],
    };
}

