/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SsoProvider } from './SsoProvider';
import {
    SsoProviderFromJSON,
    SsoProviderToJSON
} from './SsoProvider';

/**
 * A SSO User contains the information pertaining to a users SSO account.
 * @export
 * @interface SsoUser
 */
export interface SsoUser {
    /**
     * SSO ID of the user
     * @type {string}
     * @memberof SsoUser
     */
    ssoId: string;
    /**
     * 
     * @type {SsoProvider}
     * @memberof SsoUser
     */
    ssoProvider?: SsoProvider;
}

/**
 * Check if a given object implements the SsoUser interface.
 */
export function instanceOfSsoUser(value: object): value is SsoUser {
    if (!('ssoId' in value) || value['ssoId'] === undefined) return false;
    return true;
}

export function SsoUserFromJSON(json: any): SsoUser {
    return SsoUserFromJSONTyped(json, false);
}

export function SsoUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): SsoUser {
    if (json == null) {
        return json;
    }
    return {
        
        'ssoId': json['sso_id'],
        'ssoProvider': json['sso_provider'] == null ? undefined : SsoProviderFromJSON(json['sso_provider']),
    };
}

export function SsoUserToJSON(json: any): SsoUser {
    return SsoUserToJSONTyped(json, false);
}

export function SsoUserToJSONTyped(value?: SsoUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sso_id': value['ssoId'],
        'sso_provider': SsoProviderToJSON(value['ssoProvider']),
    };
}

