/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TaxPostPayloadTaxRateData } from './TaxPostPayloadTaxRateData';
import {
    TaxPostPayloadTaxRateDataFromJSON,
    TaxPostPayloadTaxRateDataToJSON
} from './TaxPostPayloadTaxRateData';

/**
 * Payload for creating a tax.
 * @export
 * @interface TaxPostPayload
 */
export interface TaxPostPayload {
    /**
     * ID of the order apply this tax to. UUID Version 4.
     * @type {string}
     * @memberof TaxPostPayload
     */
    orderId: string;
    /**
     * 
     * @type {TaxPostPayloadTaxRateData}
     * @memberof TaxPostPayload
     */
    taxRateData?: TaxPostPayloadTaxRateData;
}

/**
 * Check if a given object implements the TaxPostPayload interface.
 */
export function instanceOfTaxPostPayload(value: object): value is TaxPostPayload {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    return true;
}

export function TaxPostPayloadFromJSON(json: any): TaxPostPayload {
    return TaxPostPayloadFromJSONTyped(json, false);
}

export function TaxPostPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxPostPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['order_id'],
        'taxRateData': json['tax_rate_data'] == null ? undefined : TaxPostPayloadTaxRateDataFromJSON(json['tax_rate_data']),
    };
}

export function TaxPostPayloadToJSON(json: any): TaxPostPayload {
    return TaxPostPayloadToJSONTyped(json, false);
}

export function TaxPostPayloadToJSONTyped(value?: TaxPostPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_id': value['orderId'],
        'tax_rate_data': TaxPostPayloadTaxRateDataToJSON(value['taxRateData']),
    };
}

