/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Tax } from './Tax';
import {
    TaxFromJSON,
    TaxToJSON
} from './Tax';

/**
 * A tax response resource.
 * @export
 * @interface TaxResource
 */
export interface TaxResource {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof TaxResource
     */
    status: string;
    /**
     * 
     * @type {Tax}
     * @memberof TaxResource
     */
    data?: Tax;
}

/**
 * Check if a given object implements the TaxResource interface.
 */
export function instanceOfTaxResource(value: object): value is TaxResource {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function TaxResourceFromJSON(json: any): TaxResource {
    return TaxResourceFromJSONTyped(json, false);
}

export function TaxResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxResource {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : TaxFromJSON(json['data']),
    };
}

export function TaxResourceToJSON(json: any): TaxResource {
    return TaxResourceToJSONTyped(json, false);
}

export function TaxResourceToJSONTyped(value?: TaxResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': TaxToJSON(value['data']),
    };
}

