/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A tax rate represents the percentage of tax that should be applied to a taxed entity.
 * @export
 * @interface TaxRate
 */
export interface TaxRate {
    /**
     * String representing the object's type.
     * @type {string}
     * @memberof TaxRate
     */
    object: string;
    /**
     * ID of the tax rate. UUID Version 4.
     * @type {string}
     * @memberof TaxRate
     */
    id: string;
    /**
     * The name of the tax.
     * @type {string}
     * @memberof TaxRate
     */
    name?: string;
    /**
     * The description of the tax rate.
     * @type {string}
     * @memberof TaxRate
     */
    description?: string;
    /**
     * A decimal value representing the rate that should be applied to a taxed entity. For example, 0.075 would represent an applied tax percentage of 7.5%.
     * @type {number}
     * @memberof TaxRate
     */
    appliedRate?: number;
}

/**
 * Check if a given object implements the TaxRate interface.
 */
export function instanceOfTaxRate(value: object): value is TaxRate {
    if (!('object' in value) || value['object'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function TaxRateFromJSON(json: any): TaxRate {
    return TaxRateFromJSONTyped(json, false);
}

export function TaxRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxRate {
    if (json == null) {
        return json;
    }
    return {
        
        'object': json['object'],
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'appliedRate': json['applied_rate'] == null ? undefined : json['applied_rate'],
    };
}

export function TaxRateToJSON(json: any): TaxRate {
    return TaxRateToJSONTyped(json, false);
}

export function TaxRateToJSONTyped(value?: TaxRate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'object': value['object'],
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'applied_rate': value['appliedRate'],
    };
}

