/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A region where a company offers services. 
 * @export
 * @interface Territory
 */
export interface Territory {
    /**
     * ID of the territory. UUID Version 4.
     * @type {string}
     * @memberof Territory
     */
    id: string;
    /**
     * The name of the territory.
     * @type {string}
     * @memberof Territory
     */
    name: string;
}

/**
 * Check if a given object implements the Territory interface.
 */
export function instanceOfTerritory(value: object): value is Territory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TerritoryFromJSON(json: any): Territory {
    return TerritoryFromJSONTyped(json, false);
}

export function TerritoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Territory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function TerritoryToJSON(json: any): Territory {
    return TerritoryToJSONTyped(json, false);
}

export function TerritoryToJSONTyped(value?: Territory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

