/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressPostPayload
 */
export interface AddressPostPayload {
    /**
     * The geographic latitude of some reference point of the location, specified in degrees and decimal parts. Positive numbers must not include the plus symbol.
     * @type {number}
     * @memberof AddressPostPayload
     */
    latitude: number | null;
    /**
     * The geographic longitude of some reference point of the location, specified in degrees and decimal parts. Positive numbers must not include the plus symbol.
     * @type {number}
     * @memberof AddressPostPayload
     */
    longitude: number | null;
    /**
     * The street number portion of a location's address. In some areas, the street number may contain non-numeric characters. This field can also contain extensions and modifiers to the street number, such as '1/2' or '-B'.
     * @type {string}
     * @memberof AddressPostPayload
     */
    streetNumber?: string | null;
    /**
     * The street name portion of a location's address.
     * @type {string}
     * @memberof AddressPostPayload
     */
    streetName?: string | null;
    /**
     * The number or portion of a larger building or complex. Examples are: 'APT G', '55', etc.
     * @type {string}
     * @memberof AddressPostPayload
     */
    unitNumber?: string | null;
    /**
     * The postal code portion of a location's address.
     * @type {string}
     * @memberof AddressPostPayload
     */
    postalCode?: string | null;
    /**
     * The city of a location's address.
     * @type {string}
     * @memberof AddressPostPayload
     */
    city?: string | null;
    /**
     * A sub-section or area of a defined city. Examples would be SoHo in New York, NY, Ironbound in Newark, NJ or Inside the Beltway.
     * @type {string}
     * @memberof AddressPostPayload
     */
    cityRegion?: string | null;
    /**
     * The County, Parish or other regional authority of the location.
     * @type {string}
     * @memberof AddressPostPayload
     */
    countyOrParish?: string | null;
    /**
     * The ISO 3166-2 subdivision code for the state or province of the location. For example, “MA” for Massachusetts, United States.
     * @type {string}
     * @memberof AddressPostPayload
     */
    stateOrProvince?: string | null;
    /**
     * A sub-section or area of a defined state or province. Examples would be the Keys in FL or Hudson Valley in NY.
     * @type {string}
     * @memberof AddressPostPayload
     */
    stateOrProvinceRegion?: string | null;
    /**
     * The ISO 3166-1 country code for this for the country of the location.
     * @type {string}
     * @memberof AddressPostPayload
     */
    country?: string | null;
    /**
     * A sub-section or area of a defined country. Examples would be Napa Valley in the US, or the Amalfi Coast in Italy.
     * @type {string}
     * @memberof AddressPostPayload
     */
    countryRegion?: string | null;
}

/**
 * Check if a given object implements the AddressPostPayload interface.
 */
export function instanceOfAddressPostPayload(value: object): value is AddressPostPayload {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function AddressPostPayloadFromJSON(json: any): AddressPostPayload {
    return AddressPostPayloadFromJSONTyped(json, false);
}

export function AddressPostPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressPostPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'streetNumber': json['street_number'] == null ? undefined : json['street_number'],
        'streetName': json['street_name'] == null ? undefined : json['street_name'],
        'unitNumber': json['unit_number'] == null ? undefined : json['unit_number'],
        'postalCode': json['postal_code'] == null ? undefined : json['postal_code'],
        'city': json['city'] == null ? undefined : json['city'],
        'cityRegion': json['city_region'] == null ? undefined : json['city_region'],
        'countyOrParish': json['county_or_parish'] == null ? undefined : json['county_or_parish'],
        'stateOrProvince': json['state_or_province'] == null ? undefined : json['state_or_province'],
        'stateOrProvinceRegion': json['state_or_province_region'] == null ? undefined : json['state_or_province_region'],
        'country': json['country'] == null ? undefined : json['country'],
        'countryRegion': json['country_region'] == null ? undefined : json['country_region'],
    };
}

export function AddressPostPayloadToJSON(json: any): AddressPostPayload {
    return AddressPostPayloadToJSONTyped(json, false);
}

export function AddressPostPayloadToJSONTyped(value?: AddressPostPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'street_number': value['streetNumber'],
        'street_name': value['streetName'],
        'unit_number': value['unitNumber'],
        'postal_code': value['postalCode'],
        'city': value['city'],
        'city_region': value['cityRegion'],
        'county_or_parish': value['countyOrParish'],
        'state_or_province': value['stateOrProvince'],
        'state_or_province_region': value['stateOrProvinceRegion'],
        'country': value['country'],
        'country_region': value['countryRegion'],
    };
}

