/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A processing or validation failure returned by the API.
 * @export
 * @interface ApiFail422
 */
export interface ApiFail422 {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof ApiFail422
     */
    status: string;
}

/**
 * Check if a given object implements the ApiFail422 interface.
 */
export function instanceOfApiFail422(value: object): value is ApiFail422 {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ApiFail422FromJSON(json: any): ApiFail422 {
    return ApiFail422FromJSONTyped(json, false);
}

export function ApiFail422FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiFail422 {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function ApiFail422ToJSON(json: any): ApiFail422 {
    return ApiFail422ToJSONTyped(json, false);
}

export function ApiFail422ToJSONTyped(value?: ApiFail422 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

