/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationLinks } from './PaginationLinks';
import {
    PaginationLinksFromJSON,
    PaginationLinksFromJSONTyped,
    PaginationLinksToJSON,
    PaginationLinksToJSONTyped,
} from './PaginationLinks';
import type { CalendarDayCollectionMeta } from './CalendarDayCollectionMeta';
import {
    CalendarDayCollectionMetaFromJSON,
    CalendarDayCollectionMetaFromJSONTyped,
    CalendarDayCollectionMetaToJSON,
    CalendarDayCollectionMetaToJSONTyped,
} from './CalendarDayCollectionMeta';
import type { CalendarDay } from './CalendarDay';
import {
    CalendarDayFromJSON,
    CalendarDayFromJSONTyped,
    CalendarDayToJSON,
    CalendarDayToJSONTyped,
} from './CalendarDay';

/**
 * A collection of calendar days that have available timeslots
 * @export
 * @interface CalendarDayCollection
 */
export interface CalendarDayCollection {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof CalendarDayCollection
     */
    status: string;
    /**
     * A collection of objects.
     * @type {Array<CalendarDay>}
     * @memberof CalendarDayCollection
     */
    data?: Array<CalendarDay> | null;
    /**
     * 
     * @type {CalendarDayCollectionMeta}
     * @memberof CalendarDayCollection
     */
    meta?: CalendarDayCollectionMeta;
    /**
     * 
     * @type {PaginationLinks}
     * @memberof CalendarDayCollection
     */
    links?: PaginationLinks;
}

/**
 * Check if a given object implements the CalendarDayCollection interface.
 */
export function instanceOfCalendarDayCollection(value: object): value is CalendarDayCollection {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CalendarDayCollectionFromJSON(json: any): CalendarDayCollection {
    return CalendarDayCollectionFromJSONTyped(json, false);
}

export function CalendarDayCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalendarDayCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CalendarDayFromJSON)),
        'meta': json['meta'] == null ? undefined : CalendarDayCollectionMetaFromJSON(json['meta']),
        'links': json['links'] == null ? undefined : PaginationLinksFromJSON(json['links']),
    };
}

export function CalendarDayCollectionToJSON(json: any): CalendarDayCollection {
    return CalendarDayCollectionToJSONTyped(json, false);
}

export function CalendarDayCollectionToJSONTyped(value?: CalendarDayCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CalendarDayToJSON)),
        'meta': CalendarDayCollectionMetaToJSON(value['meta']),
        'links': PaginationLinksToJSON(value['links']),
    };
}

