/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Data to construct an ad hoc coupon inline to apply to this order. If you create a coupon upfront, pass the coupon_id parameter. Otherwise, this coupon_data will be used to scaffold a new ad hoc Coupon.
 * @export
 * @interface DiscountPostPayloadCouponData
 */
export interface DiscountPostPayloadCouponData {
    /**
     * Name of the coupon displayed to customers on orders.
     * @type {string}
     * @memberof DiscountPostPayloadCouponData
     */
    name?: string;
    /**
     * A decimal value representing the percent that will be taken off the subtotal of an order this coupon is applied to. For example, 0.500 would represent an applied discount of 50%, meaning an order with a subtotal of $100 would result in a balance of $50. Required if amount_off is null.
     * @type {number}
     * @memberof DiscountPostPayloadCouponData
     */
    percentOff?: number;
    /**
     * Amount that will be taken off the subtotal of any orders this coupon is applied to. Amount represented in the smallest currency unit (that is, 100 cents for $1.00). Required if percent_off is null.
     * @type {number}
     * @memberof DiscountPostPayloadCouponData
     */
    amountOff?: number;
}

/**
 * Check if a given object implements the DiscountPostPayloadCouponData interface.
 */
export function instanceOfDiscountPostPayloadCouponData(value: object): value is DiscountPostPayloadCouponData {
    return true;
}

export function DiscountPostPayloadCouponDataFromJSON(json: any): DiscountPostPayloadCouponData {
    return DiscountPostPayloadCouponDataFromJSONTyped(json, false);
}

export function DiscountPostPayloadCouponDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiscountPostPayloadCouponData {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'percentOff': json['percent_off'] == null ? undefined : json['percent_off'],
        'amountOff': json['amount_off'] == null ? undefined : json['amount_off'],
    };
}

export function DiscountPostPayloadCouponDataToJSON(json: any): DiscountPostPayloadCouponData {
    return DiscountPostPayloadCouponDataToJSONTyped(json, false);
}

export function DiscountPostPayloadCouponDataToJSONTyped(value?: DiscountPostPayloadCouponData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'percent_off': value['percentOff'],
        'amount_off': value['amountOff'],
    };
}

