/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DotsValue } from './DotsValue';
import {
    DotsValueFromJSON,
    DotsValueFromJSONTyped,
    DotsValueToJSON,
    DotsValueToJSONTyped,
} from './DotsValue';

/**
 * Dots representing appointments grouped by date.
 * @export
 * @interface DotsResource
 */
export interface DotsResource {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof DotsResource
     */
    status: string;
    /**
     * The number of appointments of a certain type on a specific date.
     * @type {{ [key: string]: DotsValue; }}
     * @memberof DotsResource
     */
    data?: { [key: string]: DotsValue; };
}

/**
 * Check if a given object implements the DotsResource interface.
 */
export function instanceOfDotsResource(value: object): value is DotsResource {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DotsResourceFromJSON(json: any): DotsResource {
    return DotsResourceFromJSONTyped(json, false);
}

export function DotsResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): DotsResource {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : (mapValues(json['data'], DotsValueFromJSON)),
    };
}

export function DotsResourceToJSON(json: any): DotsResource {
    return DotsResourceToJSONTyped(json, false);
}

export function DotsResourceToJSONTyped(value?: DotsResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : (mapValues(value['data'], DotsValueToJSON)),
    };
}

