/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payload for submitting a request to reset a forgotten password for a given user's email.
 * @export
 * @interface ForgotPasswordPostPayload
 */
export interface ForgotPasswordPostPayload {
    /**
     * If signing in as a customer user, the ID of company to request a password reset for.
     * @type {string}
     * @memberof ForgotPasswordPostPayload
     */
    companyId?: string;
    /**
     * Email.
     * @type {string}
     * @memberof ForgotPasswordPostPayload
     */
    email: string;
}

/**
 * Check if a given object implements the ForgotPasswordPostPayload interface.
 */
export function instanceOfForgotPasswordPostPayload(value: object): value is ForgotPasswordPostPayload {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function ForgotPasswordPostPayloadFromJSON(json: any): ForgotPasswordPostPayload {
    return ForgotPasswordPostPayloadFromJSONTyped(json, false);
}

export function ForgotPasswordPostPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordPostPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'email': json['email'],
    };
}

export function ForgotPasswordPostPayloadToJSON(json: any): ForgotPasswordPostPayload {
    return ForgotPasswordPostPayloadToJSONTyped(json, false);
}

export function ForgotPasswordPostPayloadToJSONTyped(value?: ForgotPasswordPostPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company_id': value['companyId'],
        'email': value['email'],
    };
}

