/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Group } from './Group';
import {
    GroupFromJSON,
    GroupFromJSONTyped,
    GroupToJSON,
    GroupToJSONTyped,
} from './Group';
import type { PaginationLinks } from './PaginationLinks';
import {
    PaginationLinksFromJSON,
    PaginationLinksFromJSONTyped,
    PaginationLinksToJSON,
    PaginationLinksToJSONTyped,
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * A collection of groups.
 * @export
 * @interface GroupCollection
 */
export interface GroupCollection {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof GroupCollection
     */
    status: string;
    /**
     * A collection of objects.
     * @type {Array<Group>}
     * @memberof GroupCollection
     */
    data?: Array<Group> | null;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof GroupCollection
     */
    meta?: PaginationMeta;
    /**
     * 
     * @type {PaginationLinks}
     * @memberof GroupCollection
     */
    links?: PaginationLinks;
}

/**
 * Check if a given object implements the GroupCollection interface.
 */
export function instanceOfGroupCollection(value: object): value is GroupCollection {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GroupCollectionFromJSON(json: any): GroupCollection {
    return GroupCollectionFromJSONTyped(json, false);
}

export function GroupCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(GroupFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
        'links': json['links'] == null ? undefined : PaginationLinksFromJSON(json['links']),
    };
}

export function GroupCollectionToJSON(json: any): GroupCollection {
    return GroupCollectionToJSONTyped(json, false);
}

export function GroupCollectionToJSONTyped(value?: GroupCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(GroupToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
        'links': PaginationLinksToJSON(value['links']),
    };
}

