/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Media sections to include for this listing.
 * @export
 * @interface ListingPostPayloadSections
 */
export interface ListingPostPayloadSections {
    /**
     * Include the images section when creating this listing. 
     * @type {boolean}
     * @memberof ListingPostPayloadSections
     */
    images?: boolean;
    /**
     * Include the videos section when creating this listing. 
     * @type {boolean}
     * @memberof ListingPostPayloadSections
     */
    videos?: boolean;
    /**
     * Include the floor plans section when creating this listing. 
     * @type {boolean}
     * @memberof ListingPostPayloadSections
     */
    floorPlans?: boolean;
    /**
     * Include the interactive content section when creating this listing. 
     * @type {boolean}
     * @memberof ListingPostPayloadSections
     */
    interactiveContent?: boolean;
}

/**
 * Check if a given object implements the ListingPostPayloadSections interface.
 */
export function instanceOfListingPostPayloadSections(value: object): value is ListingPostPayloadSections {
    return true;
}

export function ListingPostPayloadSectionsFromJSON(json: any): ListingPostPayloadSections {
    return ListingPostPayloadSectionsFromJSONTyped(json, false);
}

export function ListingPostPayloadSectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingPostPayloadSections {
    if (json == null) {
        return json;
    }
    return {
        
        'images': json['images'] == null ? undefined : json['images'],
        'videos': json['videos'] == null ? undefined : json['videos'],
        'floorPlans': json['floor_plans'] == null ? undefined : json['floor_plans'],
        'interactiveContent': json['interactive_content'] == null ? undefined : json['interactive_content'],
    };
}

export function ListingPostPayloadSectionsToJSON(json: any): ListingPostPayloadSections {
    return ListingPostPayloadSectionsToJSONTyped(json, false);
}

export function ListingPostPayloadSectionsToJSONTyped(value?: ListingPostPayloadSections | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'images': value['images'],
        'videos': value['videos'],
        'floor_plans': value['floorPlans'],
        'interactive_content': value['interactiveContent'],
    };
}

