/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Parcel data of the lot of a listing. Includes nearly everything about the land that makes up the listing.
 * @export
 * @interface ListingLot
 */
export interface ListingLot {
    /**
     * Total area of the lot of a listing in acres. 
     * @type {number}
     * @memberof ListingLot
     */
    sizeAcres?: number | null;
    /**
     * Number of parking spaces.
     * @type {number}
     * @memberof ListingLot
     */
    openParkingSpaces?: number | null;
}

/**
 * Check if a given object implements the ListingLot interface.
 */
export function instanceOfListingLot(value: object): value is ListingLot {
    return true;
}

export function ListingLotFromJSON(json: any): ListingLot {
    return ListingLotFromJSONTyped(json, false);
}

export function ListingLotFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingLot {
    if (json == null) {
        return json;
    }
    return {
        
        'sizeAcres': json['size_acres'] == null ? undefined : json['size_acres'],
        'openParkingSpaces': json['open_parking_spaces'] == null ? undefined : json['open_parking_spaces'],
    };
}

export function ListingLotToJSON(json: any): ListingLot {
    return ListingLotToJSONTyped(json, false);
}

export function ListingLotToJSONTyped(value?: ListingLot | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'size_acres': value['sizeAcres'],
        'open_parking_spaces': value['openParkingSpaces'],
    };
}

