/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListingPostPayloadSections } from './ListingPostPayloadSections';
import {
    ListingPostPayloadSectionsFromJSON,
    ListingPostPayloadSectionsFromJSONTyped,
    ListingPostPayloadSectionsToJSON,
    ListingPostPayloadSectionsToJSONTyped,
} from './ListingPostPayloadSections';

/**
 * Payload for creating a listing.
 * @export
 * @interface ListingPostPayload
 */
export interface ListingPostPayload {
    /**
     * ID of the address to associate with the listing. UUID Version 4.
     * @type {string}
     * @memberof ListingPostPayload
     */
    addressId: string;
    /**
     * ID of the customer to associate as the listing agent on the listing. UUID Versio
     * @type {string}
     * @memberof ListingPostPayload
     */
    listAgentId?: string;
    /**
     * ID of the customer to associate as the co-listing agent on the listing. UUID Version 4.
     * @type {string}
     * @memberof ListingPostPayload
     */
    coListAgentId?: string;
    /**
     * IDs of the orders to associate with this listing. 
     * @type {Array<string>}
     * @memberof ListingPostPayload
     */
    orderIds?: Array<string>;
    /**
     * 
     * @type {ListingPostPayloadSections}
     * @memberof ListingPostPayload
     */
    sections?: ListingPostPayloadSections;
}

/**
 * Check if a given object implements the ListingPostPayload interface.
 */
export function instanceOfListingPostPayload(value: object): value is ListingPostPayload {
    if (!('addressId' in value) || value['addressId'] === undefined) return false;
    return true;
}

export function ListingPostPayloadFromJSON(json: any): ListingPostPayload {
    return ListingPostPayloadFromJSONTyped(json, false);
}

export function ListingPostPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingPostPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'addressId': json['address_id'],
        'listAgentId': json['list_agent_id'] == null ? undefined : json['list_agent_id'],
        'coListAgentId': json['co_list_agent_id'] == null ? undefined : json['co_list_agent_id'],
        'orderIds': json['order_ids'] == null ? undefined : json['order_ids'],
        'sections': json['sections'] == null ? undefined : ListingPostPayloadSectionsFromJSON(json['sections']),
    };
}

export function ListingPostPayloadToJSON(json: any): ListingPostPayload {
    return ListingPostPayloadToJSONTyped(json, false);
}

export function ListingPostPayloadToJSONTyped(value?: ListingPostPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address_id': value['addressId'],
        'list_agent_id': value['listAgentId'],
        'co_list_agent_id': value['coListAgentId'],
        'order_ids': value['orderIds'],
        'sections': ListingPostPayloadSectionsToJSON(value['sections']),
    };
}

