/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationLinks } from './PaginationLinks';
import {
    PaginationLinksFromJSON,
    PaginationLinksFromJSONTyped,
    PaginationLinksToJSON,
    PaginationLinksToJSONTyped,
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { Listing } from './Listing';
import {
    ListingFromJSON,
    ListingFromJSONTyped,
    ListingToJSON,
    ListingToJSONTyped,
} from './Listing';

/**
 * A collection of listings.
 * @export
 * @interface ListingCollection
 */
export interface ListingCollection {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof ListingCollection
     */
    status: string;
    /**
     * A collection of objects.
     * @type {Array<Listing>}
     * @memberof ListingCollection
     */
    data?: Array<Listing> | null;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ListingCollection
     */
    meta?: PaginationMeta;
    /**
     * 
     * @type {PaginationLinks}
     * @memberof ListingCollection
     */
    links?: PaginationLinks;
}

/**
 * Check if a given object implements the ListingCollection interface.
 */
export function instanceOfListingCollection(value: object): value is ListingCollection {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ListingCollectionFromJSON(json: any): ListingCollection {
    return ListingCollectionFromJSONTyped(json, false);
}

export function ListingCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ListingFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
        'links': json['links'] == null ? undefined : PaginationLinksFromJSON(json['links']),
    };
}

export function ListingCollectionToJSON(json: any): ListingCollection {
    return ListingCollectionToJSONTyped(json, false);
}

export function ListingCollectionToJSONTyped(value?: ListingCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ListingToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
        'links': PaginationLinksToJSON(value['links']),
    };
}

