/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payload for updating a listing showcase designation.
 * @export
 * @interface ListingPutShowcasePayload
 */
export interface ListingPutShowcasePayload {
    /**
     * Is this listing a showcase listing?
     * @type {boolean}
     * @memberof ListingPutShowcasePayload
     */
    isShowcase?: boolean;
}

/**
 * Check if a given object implements the ListingPutShowcasePayload interface.
 */
export function instanceOfListingPutShowcasePayload(value: object): value is ListingPutShowcasePayload {
    return true;
}

export function ListingPutShowcasePayloadFromJSON(json: any): ListingPutShowcasePayload {
    return ListingPutShowcasePayloadFromJSONTyped(json, false);
}

export function ListingPutShowcasePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingPutShowcasePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'isShowcase': json['is_showcase'] == null ? undefined : json['is_showcase'],
    };
}

export function ListingPutShowcasePayloadToJSON(json: any): ListingPutShowcasePayload {
    return ListingPutShowcasePayloadToJSONTyped(json, false);
}

export function ListingPutShowcasePayloadToJSONTyped(value?: ListingPutShowcasePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_showcase': value['isShowcase'],
    };
}

