/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payload for updating a marketing material template record.
 * @export
 * @interface MarketingMaterialTemplateUpdatePayload
 */
export interface MarketingMaterialTemplateUpdatePayload {
    /**
     * Name of the marketing material template.
     * @type {string}
     * @memberof MarketingMaterialTemplateUpdatePayload
     */
    name?: string | null;
    /**
     * String representation of a polotno JSON object, used as the published version of the template.
     * @type {string}
     * @memberof MarketingMaterialTemplateUpdatePayload
     */
    polotnoJson?: string | null;
    /**
     * String representation of a polotno JSON object, used as the draft version of the template
     * @type {string}
     * @memberof MarketingMaterialTemplateUpdatePayload
     */
    draftPolotnoJson?: string | null;
    /**
     * The version of the MMB app used to save this record.
     * @type {string}
     * @memberof MarketingMaterialTemplateUpdatePayload
     */
    appVersion?: string | null;
    /**
     * Array of category IDs to attach to the template.
     * @type {Array<string>}
     * @memberof MarketingMaterialTemplateUpdatePayload
     */
    categoryIds?: Array<string> | null;
}

/**
 * Check if a given object implements the MarketingMaterialTemplateUpdatePayload interface.
 */
export function instanceOfMarketingMaterialTemplateUpdatePayload(value: object): value is MarketingMaterialTemplateUpdatePayload {
    return true;
}

export function MarketingMaterialTemplateUpdatePayloadFromJSON(json: any): MarketingMaterialTemplateUpdatePayload {
    return MarketingMaterialTemplateUpdatePayloadFromJSONTyped(json, false);
}

export function MarketingMaterialTemplateUpdatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketingMaterialTemplateUpdatePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'polotnoJson': json['polotno_json'] == null ? undefined : json['polotno_json'],
        'draftPolotnoJson': json['draft_polotno_json'] == null ? undefined : json['draft_polotno_json'],
        'appVersion': json['app_version'] == null ? undefined : json['app_version'],
        'categoryIds': json['category_ids'] == null ? undefined : json['category_ids'],
    };
}

export function MarketingMaterialTemplateUpdatePayloadToJSON(json: any): MarketingMaterialTemplateUpdatePayload {
    return MarketingMaterialTemplateUpdatePayloadToJSONTyped(json, false);
}

export function MarketingMaterialTemplateUpdatePayloadToJSONTyped(value?: MarketingMaterialTemplateUpdatePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'polotno_json': value['polotnoJson'],
        'draft_polotno_json': value['draftPolotnoJson'],
        'app_version': value['appVersion'],
        'category_ids': value['categoryIds'],
    };
}

