/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Payload for storing a new marketing material template record.
 * @export
 * @interface MarketingMaterialTemplateStorePayload
 */
export interface MarketingMaterialTemplateStorePayload {
    /**
     * The name of the template.
     * @type {string}
     * @memberof MarketingMaterialTemplateStorePayload
     */
    name?: string | null;
    /**
     * String representation of a polotno JSON object, used as the published version of the template.
     * @type {string}
     * @memberof MarketingMaterialTemplateStorePayload
     */
    polotnoJson?: string | null;
    /**
     * String representation of a polotno JSON object, used as the draft version of the template.
     * @type {string}
     * @memberof MarketingMaterialTemplateStorePayload
     */
    draftPolotnoJson?: string | null;
    /**
     * The ID of the group that the template belongs to. UUID Version 4.
     * @type {string}
     * @memberof MarketingMaterialTemplateStorePayload
     */
    groupId?: string | null;
}

/**
 * Check if a given object implements the MarketingMaterialTemplateStorePayload interface.
 */
export function instanceOfMarketingMaterialTemplateStorePayload(value: object): value is MarketingMaterialTemplateStorePayload {
    return true;
}

export function MarketingMaterialTemplateStorePayloadFromJSON(json: any): MarketingMaterialTemplateStorePayload {
    return MarketingMaterialTemplateStorePayloadFromJSONTyped(json, false);
}

export function MarketingMaterialTemplateStorePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketingMaterialTemplateStorePayload {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'polotnoJson': json['polotno_json'] == null ? undefined : json['polotno_json'],
        'draftPolotnoJson': json['draft_polotno_json'] == null ? undefined : json['draft_polotno_json'],
        'groupId': json['group_id'] == null ? undefined : json['group_id'],
    };
}

export function MarketingMaterialTemplateStorePayloadToJSON(json: any): MarketingMaterialTemplateStorePayload {
    return MarketingMaterialTemplateStorePayloadToJSONTyped(json, false);
}

export function MarketingMaterialTemplateStorePayloadToJSONTyped(value?: MarketingMaterialTemplateStorePayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'polotno_json': value['polotnoJson'],
        'draft_polotno_json': value['draftPolotnoJson'],
        'group_id': value['groupId'],
    };
}

