/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MarketingMaterialTemplate } from './MarketingMaterialTemplate';
import {
    MarketingMaterialTemplateFromJSON,
    MarketingMaterialTemplateFromJSONTyped,
    MarketingMaterialTemplateToJSON,
    MarketingMaterialTemplateToJSONTyped,
} from './MarketingMaterialTemplate';

/**
 * A marketing material template.
 * @export
 * @interface MarketingMaterialTemplateResource
 */
export interface MarketingMaterialTemplateResource {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof MarketingMaterialTemplateResource
     */
    status: string;
    /**
     * 
     * @type {MarketingMaterialTemplate}
     * @memberof MarketingMaterialTemplateResource
     */
    data?: MarketingMaterialTemplate;
}

/**
 * Check if a given object implements the MarketingMaterialTemplateResource interface.
 */
export function instanceOfMarketingMaterialTemplateResource(value: object): value is MarketingMaterialTemplateResource {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function MarketingMaterialTemplateResourceFromJSON(json: any): MarketingMaterialTemplateResource {
    return MarketingMaterialTemplateResourceFromJSONTyped(json, false);
}

export function MarketingMaterialTemplateResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketingMaterialTemplateResource {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : MarketingMaterialTemplateFromJSON(json['data']),
    };
}

export function MarketingMaterialTemplateResourceToJSON(json: any): MarketingMaterialTemplateResource {
    return MarketingMaterialTemplateResourceToJSONTyped(json, false);
}

export function MarketingMaterialTemplateResourceToJSONTyped(value?: MarketingMaterialTemplateResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': MarketingMaterialTemplateToJSON(value['data']),
    };
}

