/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationLinks } from './PaginationLinks';
import {
    PaginationLinksFromJSON,
    PaginationLinksFromJSONTyped,
    PaginationLinksToJSON,
    PaginationLinksToJSONTyped,
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { MarketingMaterialPageSize } from './MarketingMaterialPageSize';
import {
    MarketingMaterialPageSizeFromJSON,
    MarketingMaterialPageSizeFromJSONTyped,
    MarketingMaterialPageSizeToJSON,
    MarketingMaterialPageSizeToJSONTyped,
} from './MarketingMaterialPageSize';

/**
 * A collection of marketing material page sizes.
 * @export
 * @interface MarketingMaterialPageSizeCollection
 */
export interface MarketingMaterialPageSizeCollection {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof MarketingMaterialPageSizeCollection
     */
    status: string;
    /**
     * A collection of objects.
     * @type {Array<MarketingMaterialPageSize>}
     * @memberof MarketingMaterialPageSizeCollection
     */
    data?: Array<MarketingMaterialPageSize> | null;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof MarketingMaterialPageSizeCollection
     */
    meta?: PaginationMeta;
    /**
     * 
     * @type {PaginationLinks}
     * @memberof MarketingMaterialPageSizeCollection
     */
    links?: PaginationLinks;
}

/**
 * Check if a given object implements the MarketingMaterialPageSizeCollection interface.
 */
export function instanceOfMarketingMaterialPageSizeCollection(value: object): value is MarketingMaterialPageSizeCollection {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function MarketingMaterialPageSizeCollectionFromJSON(json: any): MarketingMaterialPageSizeCollection {
    return MarketingMaterialPageSizeCollectionFromJSONTyped(json, false);
}

export function MarketingMaterialPageSizeCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketingMaterialPageSizeCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MarketingMaterialPageSizeFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
        'links': json['links'] == null ? undefined : PaginationLinksFromJSON(json['links']),
    };
}

export function MarketingMaterialPageSizeCollectionToJSON(json: any): MarketingMaterialPageSizeCollection {
    return MarketingMaterialPageSizeCollectionToJSONTyped(json, false);
}

export function MarketingMaterialPageSizeCollectionToJSONTyped(value?: MarketingMaterialPageSizeCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MarketingMaterialPageSizeToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
        'links': PaginationLinksToJSON(value['links']),
    };
}

