/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A marketing material category.
 * @export
 * @interface MarketingMaterialCategory
 */
export interface MarketingMaterialCategory {
    /**
     * ID of the category. UUID Version 4.
     * @type {string}
     * @memberof MarketingMaterialCategory
     */
    id: string;
    /**
     * Slug of the category.
     * @type {string}
     * @memberof MarketingMaterialCategory
     */
    slug: string;
    /**
     * Name of the category.
     * @type {string}
     * @memberof MarketingMaterialCategory
     */
    name: string;
}

/**
 * Check if a given object implements the MarketingMaterialCategory interface.
 */
export function instanceOfMarketingMaterialCategory(value: object): value is MarketingMaterialCategory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MarketingMaterialCategoryFromJSON(json: any): MarketingMaterialCategory {
    return MarketingMaterialCategoryFromJSONTyped(json, false);
}

export function MarketingMaterialCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarketingMaterialCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'slug': json['slug'],
        'name': json['name'],
    };
}

export function MarketingMaterialCategoryToJSON(json: any): MarketingMaterialCategory {
    return MarketingMaterialCategoryToJSONTyped(json, false);
}

export function MarketingMaterialCategoryToJSONTyped(value?: MarketingMaterialCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
    };
}

