/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationPreference } from './NotificationPreference';
import {
    NotificationPreferenceFromJSON,
    NotificationPreferenceFromJSONTyped,
    NotificationPreferenceToJSON,
    NotificationPreferenceToJSONTyped,
} from './NotificationPreference';

/**
 * A request to change the user's notification preferences.
 * @export
 * @interface NotificationPreferencesPutPayload
 */
export interface NotificationPreferencesPutPayload {
    /**
     * A notification preference.
     * @type {Array<NotificationPreference>}
     * @memberof NotificationPreferencesPutPayload
     */
    preferences: Array<NotificationPreference> | null;
}

/**
 * Check if a given object implements the NotificationPreferencesPutPayload interface.
 */
export function instanceOfNotificationPreferencesPutPayload(value: object): value is NotificationPreferencesPutPayload {
    if (!('preferences' in value) || value['preferences'] === undefined) return false;
    return true;
}

export function NotificationPreferencesPutPayloadFromJSON(json: any): NotificationPreferencesPutPayload {
    return NotificationPreferencesPutPayloadFromJSONTyped(json, false);
}

export function NotificationPreferencesPutPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationPreferencesPutPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'preferences': (json['preferences'] == null ? null : (json['preferences'] as Array<any>).map(NotificationPreferenceFromJSON)),
    };
}

export function NotificationPreferencesPutPayloadToJSON(json: any): NotificationPreferencesPutPayload {
    return NotificationPreferencesPutPayloadToJSONTyped(json, false);
}

export function NotificationPreferencesPutPayloadToJSONTyped(value?: NotificationPreferencesPutPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'preferences': (value['preferences'] == null ? null : (value['preferences'] as Array<any>).map(NotificationPreferenceToJSON)),
    };
}

