/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * An order item.
 * @export
 * @interface OrderItemResource
 */
export interface OrderItemResource {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof OrderItemResource
     */
    status: string;
    /**
     * 
     * @type {OrderItem}
     * @memberof OrderItemResource
     */
    data?: OrderItem;
}

/**
 * Check if a given object implements the OrderItemResource interface.
 */
export function instanceOfOrderItemResource(value: object): value is OrderItemResource {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function OrderItemResourceFromJSON(json: any): OrderItemResource {
    return OrderItemResourceFromJSONTyped(json, false);
}

export function OrderItemResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItemResource {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : OrderItemFromJSON(json['data']),
    };
}

export function OrderItemResourceToJSON(json: any): OrderItemResource {
    return OrderItemResourceToJSONTyped(json, false);
}

export function OrderItemResourceToJSONTyped(value?: OrderItemResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': OrderItemToJSON(value['data']),
    };
}

