/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Settings for hidding or showing certain steps of the order form during the booking process. Note, steps can only be hidden if all required information is supplied in the OrderFormSession.
 * @export
 * @interface OrderFormSessionStepVisibility
 */
export interface OrderFormSessionStepVisibility {
    /**
     * If the address step is hidden or shown during the booking process. Only applicable if address_id or address_data parameters are set.
     * @type {boolean}
     * @memberof OrderFormSessionStepVisibility
     */
    showAddressStep?: boolean;
    /**
     * If the customer step is hidden or shown during the booking process. Only applicable if customer_id or customer_data parameters are set.
     * @type {boolean}
     * @memberof OrderFormSessionStepVisibility
     */
    showCustomerStep?: boolean;
}

/**
 * Check if a given object implements the OrderFormSessionStepVisibility interface.
 */
export function instanceOfOrderFormSessionStepVisibility(value: object): value is OrderFormSessionStepVisibility {
    return true;
}

export function OrderFormSessionStepVisibilityFromJSON(json: any): OrderFormSessionStepVisibility {
    return OrderFormSessionStepVisibilityFromJSONTyped(json, false);
}

export function OrderFormSessionStepVisibilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderFormSessionStepVisibility {
    if (json == null) {
        return json;
    }
    return {
        
        'showAddressStep': json['show_address_step'] == null ? undefined : json['show_address_step'],
        'showCustomerStep': json['show_customer_step'] == null ? undefined : json['show_customer_step'],
    };
}

export function OrderFormSessionStepVisibilityToJSON(json: any): OrderFormSessionStepVisibility {
    return OrderFormSessionStepVisibilityToJSONTyped(json, false);
}

export function OrderFormSessionStepVisibilityToJSONTyped(value?: OrderFormSessionStepVisibility | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'show_address_step': value['showAddressStep'],
        'show_customer_step': value['showCustomerStep'],
    };
}

