/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A request to change the currently authenticated user's password.
 * @export
 * @interface OrderTagsPutPayload
 */
export interface OrderTagsPutPayload {
    /**
     * Array of tag IDs to attach to the order.
     * @type {Array<string>}
     * @memberof OrderTagsPutPayload
     */
    tagIds: Array<string>;
}

/**
 * Check if a given object implements the OrderTagsPutPayload interface.
 */
export function instanceOfOrderTagsPutPayload(value: object): value is OrderTagsPutPayload {
    if (!('tagIds' in value) || value['tagIds'] === undefined) return false;
    return true;
}

export function OrderTagsPutPayloadFromJSON(json: any): OrderTagsPutPayload {
    return OrderTagsPutPayloadFromJSONTyped(json, false);
}

export function OrderTagsPutPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderTagsPutPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'tagIds': json['tag_ids'],
    };
}

export function OrderTagsPutPayloadToJSON(json: any): OrderTagsPutPayload {
    return OrderTagsPutPayloadToJSONTyped(json, false);
}

export function OrderTagsPutPayloadToJSONTyped(value?: OrderTagsPutPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag_ids': value['tagIds'],
    };
}

