/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Data used to generate or retrieve a Customer object inline. If you create an customer upfront, pass the customer_id parameter. Otherwise, this customer_data will be used to scaffold a new Customer (Group) object, if present.
 * @export
 * @interface OrderFormSessionPostPayloadCustomerData
 */
export interface OrderFormSessionPostPayloadCustomerData {
    /**
     * Single sign on identifier of the customer user. 
     * @type {string}
     * @memberof OrderFormSessionPostPayloadCustomerData
     */
    ssoId?: string;
    /**
     * Email address of the user.
     * @type {string}
     * @memberof OrderFormSessionPostPayloadCustomerData
     */
    email?: string;
    /**
     * First name of the user.
     * @type {string}
     * @memberof OrderFormSessionPostPayloadCustomerData
     */
    firstName?: string | null;
    /**
     * Last name of the user.
     * @type {string}
     * @memberof OrderFormSessionPostPayloadCustomerData
     */
    lastName?: string | null;
    /**
     * A phone number represented in whichever standards specified by the user, typically ###-###-#### (separated by hyphens).
     * @type {string}
     * @memberof OrderFormSessionPostPayloadCustomerData
     */
    phone?: string | null;
}

/**
 * Check if a given object implements the OrderFormSessionPostPayloadCustomerData interface.
 */
export function instanceOfOrderFormSessionPostPayloadCustomerData(value: object): value is OrderFormSessionPostPayloadCustomerData {
    return true;
}

export function OrderFormSessionPostPayloadCustomerDataFromJSON(json: any): OrderFormSessionPostPayloadCustomerData {
    return OrderFormSessionPostPayloadCustomerDataFromJSONTyped(json, false);
}

export function OrderFormSessionPostPayloadCustomerDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderFormSessionPostPayloadCustomerData {
    if (json == null) {
        return json;
    }
    return {
        
        'ssoId': json['sso_id'] == null ? undefined : json['sso_id'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function OrderFormSessionPostPayloadCustomerDataToJSON(json: any): OrderFormSessionPostPayloadCustomerData {
    return OrderFormSessionPostPayloadCustomerDataToJSONTyped(json, false);
}

export function OrderFormSessionPostPayloadCustomerDataToJSONTyped(value?: OrderFormSessionPostPayloadCustomerData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sso_id': value['ssoId'],
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'phone': value['phone'],
    };
}

