/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Metadata about a paginated response.
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * Total number of records.
     * @type {number}
     * @memberof PaginationMeta
     */
    total: number;
    /**
     * Number of records per page.
     * @type {number}
     * @memberof PaginationMeta
     */
    perPage: number;
    /**
     * The current page.
     * @type {number}
     * @memberof PaginationMeta
     */
    currentPage: number;
    /**
     * The last page of records.
     * @type {number}
     * @memberof PaginationMeta
     */
    lastPage: number;
    /**
     * The ID of the first record on this page. This is specified as either `integer` or `null` purely for spec testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand.
     * @type {number}
     * @memberof PaginationMeta
     */
    from?: number | null;
    /**
     * The ID of the last record on this page. This is specified as either `integer` or `null` purely for spec testing purposes. The model which is autogenerated from this definition will be thrown out and written by-hand.
     * @type {number}
     * @memberof PaginationMeta
     */
    to?: number | null;
    /**
     * The current paged path.
     * @type {string}
     * @memberof PaginationMeta
     */
    path: string;
}

/**
 * Check if a given object implements the PaginationMeta interface.
 */
export function instanceOfPaginationMeta(value: object): value is PaginationMeta {
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('perPage' in value) || value['perPage'] === undefined) return false;
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('lastPage' in value) || value['lastPage'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
    return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'],
        'perPage': json['per_page'],
        'currentPage': json['current_page'],
        'lastPage': json['last_page'],
        'from': json['from'] == null ? undefined : json['from'],
        'to': json['to'] == null ? undefined : json['to'],
        'path': json['path'],
    };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
    return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(value?: PaginationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'per_page': value['perPage'],
        'current_page': value['currentPage'],
        'last_page': value['lastPage'],
        'from': value['from'],
        'to': value['to'],
        'path': value['path'],
    };
}

