/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonalAccessTokenCustomer } from './PersonalAccessTokenCustomer';
import {
    PersonalAccessTokenCustomerFromJSON,
    PersonalAccessTokenCustomerFromJSONTyped,
    PersonalAccessTokenCustomerToJSON,
    PersonalAccessTokenCustomerToJSONTyped,
} from './PersonalAccessTokenCustomer';

/**
 * A personal access token.
 * @export
 * @interface PersonalAccessTokenCustomerResource
 */
export interface PersonalAccessTokenCustomerResource {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof PersonalAccessTokenCustomerResource
     */
    status: string;
    /**
     * 
     * @type {PersonalAccessTokenCustomer}
     * @memberof PersonalAccessTokenCustomerResource
     */
    data?: PersonalAccessTokenCustomer;
}

/**
 * Check if a given object implements the PersonalAccessTokenCustomerResource interface.
 */
export function instanceOfPersonalAccessTokenCustomerResource(value: object): value is PersonalAccessTokenCustomerResource {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PersonalAccessTokenCustomerResourceFromJSON(json: any): PersonalAccessTokenCustomerResource {
    return PersonalAccessTokenCustomerResourceFromJSONTyped(json, false);
}

export function PersonalAccessTokenCustomerResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalAccessTokenCustomerResource {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : PersonalAccessTokenCustomerFromJSON(json['data']),
    };
}

export function PersonalAccessTokenCustomerResourceToJSON(json: any): PersonalAccessTokenCustomerResource {
    return PersonalAccessTokenCustomerResourceToJSONTyped(json, false);
}

export function PersonalAccessTokenCustomerResourceToJSONTyped(value?: PersonalAccessTokenCustomerResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': PersonalAccessTokenCustomerToJSON(value['data']),
    };
}

