/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationLinks } from './PaginationLinks';
import {
    PaginationLinksFromJSON,
    PaginationLinksFromJSONTyped,
    PaginationLinksToJSON,
    PaginationLinksToJSONTyped,
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
    ProductToJSONTyped,
} from './Product';

/**
 * A collection of products.
 * @export
 * @interface ProductCollection
 */
export interface ProductCollection {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof ProductCollection
     */
    status: string;
    /**
     * A collection of objects.
     * @type {Array<Product>}
     * @memberof ProductCollection
     */
    data?: Array<Product> | null;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof ProductCollection
     */
    meta?: PaginationMeta;
    /**
     * 
     * @type {PaginationLinks}
     * @memberof ProductCollection
     */
    links?: PaginationLinks;
}

/**
 * Check if a given object implements the ProductCollection interface.
 */
export function instanceOfProductCollection(value: object): value is ProductCollection {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ProductCollectionFromJSON(json: any): ProductCollection {
    return ProductCollectionFromJSONTyped(json, false);
}

export function ProductCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ProductFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
        'links': json['links'] == null ? undefined : PaginationLinksFromJSON(json['links']),
    };
}

export function ProductCollectionToJSON(json: any): ProductCollection {
    return ProductCollectionToJSONTyped(json, false);
}

export function ProductCollectionToJSONTyped(value?: ProductCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ProductToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
        'links': PaginationLinksToJSON(value['links']),
    };
}

