/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A category for products.
 * @export
 * @interface ProductCategory
 */
export interface ProductCategory {
    /**
     * ID of the product category. UUID Version 4.
     * @type {string}
     * @memberof ProductCategory
     */
    id: string;
    /**
     * The title of the product category.
     * @type {string}
     * @memberof ProductCategory
     */
    title: string;
}

/**
 * Check if a given object implements the ProductCategory interface.
 */
export function instanceOfProductCategory(value: object): value is ProductCategory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ProductCategoryFromJSON(json: any): ProductCategory {
    return ProductCategoryFromJSONTyped(json, false);
}

export function ProductCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
    };
}

export function ProductCategoryToJSON(json: any): ProductCategory {
    return ProductCategoryToJSONTyped(json, false);
}

export function ProductCategoryToJSONTyped(value?: ProductCategory | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
    };
}

