/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Data to construct an ad hoc tax rate inline to apply to this order.
 * @export
 * @interface TaxPostPayloadTaxRateData
 */
export interface TaxPostPayloadTaxRateData {
    /**
     * The name of the tax.
     * @type {string}
     * @memberof TaxPostPayloadTaxRateData
     */
    name?: string;
    /**
     * The description of the tax rate.
     * @type {string}
     * @memberof TaxPostPayloadTaxRateData
     */
    description?: string;
    /**
     * A decimal value representing the rate that should be applied to a taxed entity. For example, 0.075 would represent an applied tax percentage of 7.5%.
     * @type {number}
     * @memberof TaxPostPayloadTaxRateData
     */
    appliedRate?: number;
}

/**
 * Check if a given object implements the TaxPostPayloadTaxRateData interface.
 */
export function instanceOfTaxPostPayloadTaxRateData(value: object): value is TaxPostPayloadTaxRateData {
    return true;
}

export function TaxPostPayloadTaxRateDataFromJSON(json: any): TaxPostPayloadTaxRateData {
    return TaxPostPayloadTaxRateDataFromJSONTyped(json, false);
}

export function TaxPostPayloadTaxRateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxPostPayloadTaxRateData {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'appliedRate': json['applied_rate'] == null ? undefined : json['applied_rate'],
    };
}

export function TaxPostPayloadTaxRateDataToJSON(json: any): TaxPostPayloadTaxRateData {
    return TaxPostPayloadTaxRateDataToJSONTyped(json, false);
}

export function TaxPostPayloadTaxRateDataToJSONTyped(value?: TaxPostPayloadTaxRateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'applied_rate': value['appliedRate'],
    };
}

