/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * A user.
 * @export
 * @interface UserResource
 */
export interface UserResource {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof UserResource
     */
    status: string;
    /**
     * 
     * @type {User}
     * @memberof UserResource
     */
    data?: User;
}

/**
 * Check if a given object implements the UserResource interface.
 */
export function instanceOfUserResource(value: object): value is UserResource {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UserResourceFromJSON(json: any): UserResource {
    return UserResourceFromJSONTyped(json, false);
}

export function UserResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResource {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : UserFromJSON(json['data']),
    };
}

export function UserResourceToJSON(json: any): UserResource {
    return UserResourceToJSONTyped(json, false);
}

export function UserResourceToJSONTyped(value?: UserResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': UserToJSON(value['data']),
    };
}

