/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Video } from './Video';
import {
    VideoFromJSON,
    VideoFromJSONTyped,
    VideoToJSON,
    VideoToJSONTyped,
} from './Video';

/**
 * A video.
 * @export
 * @interface VideoResource
 */
export interface VideoResource {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof VideoResource
     */
    status: string;
    /**
     * 
     * @type {Video}
     * @memberof VideoResource
     */
    data?: Video;
}

/**
 * Check if a given object implements the VideoResource interface.
 */
export function instanceOfVideoResource(value: object): value is VideoResource {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function VideoResourceFromJSON(json: any): VideoResource {
    return VideoResourceFromJSONTyped(json, false);
}

export function VideoResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoResource {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : VideoFromJSON(json['data']),
    };
}

export function VideoResourceToJSON(json: any): VideoResource {
    return VideoResourceToJSONTyped(json, false);
}

export function VideoResourceToJSONTyped(value?: VideoResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': VideoToJSON(value['data']),
    };
}

