/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationLinks } from './PaginationLinks';
import {
    PaginationLinksFromJSON,
    PaginationLinksFromJSONTyped,
    PaginationLinksToJSON,
    PaginationLinksToJSONTyped,
} from './PaginationLinks';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { VonageMessage } from './VonageMessage';
import {
    VonageMessageFromJSON,
    VonageMessageFromJSONTyped,
    VonageMessageToJSON,
    VonageMessageToJSONTyped,
} from './VonageMessage';

/**
 * A collection of messages.
 * @export
 * @interface VonageMessageCollection
 */
export interface VonageMessageCollection {
    /**
     * What was the state of the request?
     * @type {string}
     * @memberof VonageMessageCollection
     */
    status: string;
    /**
     * A collection of objects.
     * @type {Array<VonageMessage>}
     * @memberof VonageMessageCollection
     */
    data?: Array<VonageMessage> | null;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof VonageMessageCollection
     */
    meta?: PaginationMeta;
    /**
     * 
     * @type {PaginationLinks}
     * @memberof VonageMessageCollection
     */
    links?: PaginationLinks;
}

/**
 * Check if a given object implements the VonageMessageCollection interface.
 */
export function instanceOfVonageMessageCollection(value: object): value is VonageMessageCollection {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function VonageMessageCollectionFromJSON(json: any): VonageMessageCollection {
    return VonageMessageCollectionFromJSONTyped(json, false);
}

export function VonageMessageCollectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): VonageMessageCollection {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(VonageMessageFromJSON)),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
        'links': json['links'] == null ? undefined : PaginationLinksFromJSON(json['links']),
    };
}

export function VonageMessageCollectionToJSON(json: any): VonageMessageCollection {
    return VonageMessageCollectionToJSONTyped(json, false);
}

export function VonageMessageCollectionToJSONTyped(value?: VonageMessageCollection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(VonageMessageToJSON)),
        'meta': PaginationMetaToJSON(value['meta']),
        'links': PaginationLinksToJSON(value['links']),
    };
}

