/* tslint:disable */
/* eslint-disable */
/**
 * Aryeo
 * # Introduction The Aryeo API provides access to the Aryeo platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: jarrodp@zillowgroup.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Valuation data relating to the price of a listing.
 * @export
 * @interface VonageMessage
 */
export interface VonageMessage {
    /**
     * The name (source) of the message.
     * @type {string}
     * @memberof VonageMessage
     */
    name?: string | null;
    /**
     * The date and time (ISO 8601 format) when the message was created.
     * @type {Date}
     * @memberof VonageMessage
     */
    createdAt?: Date | null;
    /**
     * The date and time (ISO 8601 format) when the message was last updated.
     * @type {Date}
     * @memberof VonageMessage
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the VonageMessage interface.
 */
export function instanceOfVonageMessage(value: object): value is VonageMessage {
    return true;
}

export function VonageMessageFromJSON(json: any): VonageMessage {
    return VonageMessageFromJSONTyped(json, false);
}

export function VonageMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): VonageMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function VonageMessageToJSON(json: any): VonageMessage {
    return VonageMessageToJSONTyped(json, false);
}

export function VonageMessageToJSONTyped(value?: VonageMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt'] as any).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt'] as any).toISOString()),
    };
}

